
PARCC_Data_LONG <- rbindlist(list(
      dbGetQuery(dbConnect(SQLite(), dbname = parcc.db), "select YEAR, CONTENT_AREA, GRADE, VALID_CASE, SCALE_SCORE, SCALE_SCORE_CSEM from PARCC_Data_LONG_2015_2"), # SCALE_SCORE_ACTUAL, SCALE_SCORE_CSEM_ACTUAL,
      dbGetQuery(dbConnect(SQLite(), dbname = parcc.db), "select YEAR, CONTENT_AREA, GRADE, VALID_CASE, SCALE_SCORE, SCALE_SCORE_CSEM from PARCC_Data_LONG_2016_1"),
      dbGetQuery(dbConnect(SQLite(), dbname = parcc.db), "select YEAR, CONTENT_AREA, GRADE, VALID_CASE, SCALE_SCORE, SCALE_SCORE_CSEM from PARCC_Data_LONG_2016_2"),
      dbGetQuery(dbConnect(SQLite(), dbname = parcc.db), "select YEAR, CONTENT_AREA, GRADE, VALID_CASE, SCALE_SCORE, SCALE_SCORE_CSEM from PARCC_Data_LONG_2017_1"),
      dbGetQuery(dbConnect(SQLite(), dbname = parcc.db), "select YEAR, CONTENT_AREA, GRADE, VALID_CASE, SCALE_SCORE, SCALE_SCORE_CSEM from PARCC_Data_LONG_2017_2"),
			dbGetQuery(dbConnect(SQLite(), dbname = parcc.db), "select YEAR, CONTENT_AREA, GRADE, VALID_CASE, SCALE_SCORE, SCALE_SCORE_CSEM from PARCC_Data_LONG_2018_1"),
			dbGetQuery(dbConnect(SQLite(), dbname = parcc.db), "select YEAR, CONTENT_AREA, GRADE, VALID_CASE, SCALE_SCORE, SCALE_SCORE_CSEM from PARCC_Data_LONG_2018_2")))

PARCC_Data_LONG <- PARCC_Data_LONG[VALID_CASE == "VALID_CASE",]
PARCC_Data_LONG[, VALID_CASE := NULL]

setkey(PARCC_Data_LONG, YEAR, CONTENT_AREA, GRADE, SCALE_SCORE)
PARCC_SS_CSEM_LOOKUP <- PARCC_Data_LONG[grep("_SS", CONTENT_AREA),][, list(SCALE_SCORE_CSEM = mean(SCALE_SCORE_CSEM)), by = key(PARCC_Data_LONG)]
PARCC_THETA_CSEM_LOOKUP <- PARCC_Data_LONG[grep("_SS", CONTENT_AREA, invert =TRUE),][, list(SCALE_SCORE_CSEM = mean(SCALE_SCORE_CSEM)), by = key(PARCC_Data_LONG)]

save(PARCC_SS_CSEM_LOOKUP, file="/media/Data/Dropbox (SGP)/SGP/PARCC/PARCC/Data/Base_Files/PARCC_SS_CSEM_LOOKUP.rda")
save(PARCC_THETA_CSEM_LOOKUP, file="/media/Data/Dropbox (SGP)/SGP/PARCC/PARCC/Data/Base_Files/PARCC_THETA_CSEM_LOOKUP.rda")

#####
#####
#####

setkey(PARCC_Data_LONG, YEAR, CONTENT_AREA, GRADE, SCALE_SCORE_ACTUAL)
PARCC_SS_CSEM_LOOKUP <- PARCC_Data_LONG[, list(SCALE_SCORE_CSEM_ACTUAL = mean(SCALE_SCORE_CSEM_ACTUAL, na.rm=TRUE)), by = key(PARCC_Data_LONG)]


# setkey(PARCC_Data_LONG, YEAR, CONTENT_AREA, GRADE, SCALE_SCORE_ACTUAL, SCALE_SCORE_CSEM_ACTUAL)

setkey(PARCC_Data_LONG, YEAR, CONTENT_AREA, GRADE, SCALE_SCORE, SCALE_SCORE_CSEM)
PARCC_CSEM_LOOKUP <- unique(PARCC_Data_LONG, by = key(PARCC_Data_LONG))

setkey(PARCC_Data_LONG, YEAR, CONTENT_AREA, GRADE, SCALE_SCORE)
PARCC_CSEM_LOOKUP2 <- unique(PARCC_Data_LONG, by = key(PARCC_Data_LONG))

setkeyv(PARCC_CSEM_LOOKUP, key(PARCC_CSEM_LOOKUP2))
table(duplicated(PARCC_CSEM_LOOKUP))


table(duplicated(PARCC_CSEM_LOOKUP[CONTENT_AREA=="ALGEBRA_I" & YEAR == "2015_2016.2", SCALE_SCORE_ACTUAL]))
table(duplicated(PARCC_CSEM_LOOKUP[CONTENT_AREA=="ALGEBRA_I" & YEAR == "2016_2017.2", SCALE_SCORE_ACTUAL]))

PARCC_CSEM_LOOKUP[CONTENT_AREA=="ALGEBRA_I" & YEAR == "2016_2017.2", SCALE_SCORE][which(duplicated(PARCC_CSEM_LOOKUP[CONTENT_AREA=="ALGEBRA_I" & YEAR == "2016_2017.2", SCALE_SCORE]))]
PARCC_CSEM_LOOKUP[CONTENT_AREA=="ALGEBRA_I" & YEAR == "2016_2017.2" & SCALE_SCORE==2.4271,]



PARCC_CSEM_LOOKUP[CONTENT_AREA=="ALGEBRA_I", list(YEAR, CONTENT_AREA, GRADE, SCALE_SCORE_ACTUAL, SCALE_SCORE_CSEM_ACTUAL)]
